version: "3"
services:

  esdeka-gameserverl4d2:
    container_name: L4D2
    environment:
      - TZ=Europe/Brussels
      - SRCDS_PORT=27015
      - SRCDS_SRV_DIR=/home/steam/left4dead2
      - SRCDS_APP_ID=222860
      - SOURCEMOD_VERSION_MAJOR=1.11
      - SOURCEMOD_VERSION_MINOR=0
      - SOURCEMOD_BUILD=6863
      - METAMOD_VERSION_MAJOR=1.12
      - METAMOD_VERSION_MINOR=0
      - METAMOD_BUILD=1157
      - COLLECTIONS=2787108777 2787147130
      - gid=100
      - uid=1026
    expose:
      - 27005/tcp
      - 27005/udp
      - 27015/tcp
      - 27015/udp
      - 27020/tcp
      - 27020/udp
      - 51840/tcp
    image: esdeka/gameserverl4d2:latest
    ports:
      - 27005:27005
      - 27005:27005/udp
      - 27015:27015
      - 27015:27015/udp
      - 27020:27020
      - 51840:51840
    restart: unless-stopped
    volumes:
      - /volume1/docker/gameserverl4d2:/home/steam/left4dead2:rw
    stdin_open: true # docker run -i
    tty: true        # docker run -t