version: "3"
services:

  watchtower:
    command:
      - --cleanup
      - --label-enable
    container_name: watchtower
    image: containrrr/watchtower:latest
    labels:
      com.centurylinklabs.watchtower: true
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
