version: '3.5'
services:

  dontstarvetogether:
    container_name: DontStarve-Together
    image: jamesits/dst-server:latest
    environment:
      - TZ=Europe/Brussels
    restart: "on-failure:5"
    ports:
      - "10999-11000:10999-11000/udp"
      - "12346-12347:12346-12347/udp"
    volumes:
      - /volume1/docker/dontstarvetogether:/data
    stop_grace_period: 6m