version: "3"
services:

  archisteamfarm:
    image: justarchi/archisteamfarm:latest
    container_name: ASF
    environment:
      - TZ=Europe/Brussels
    volumes:
      - /volume1/docker/asf/config:/app/config
      - /volume1/docker/asf/logs:/app/logs
    ports:
      - 1242:1242
    restart: unless-stopped
  archisteamfarmsdklog:
    image: justarchi/archisteamfarm:latest
    environment:
      - TZ=Europe/Brussels
    container_name: ASFsdklog
    volumes:
      - /volume1/docker/archisteamfarmsdklog/Nlog.config:/app/NLog.config
      - /volume1/docker/archisteamfarmsdklog/config:/app/config
      - /volume1/docker/archisteamfarmsdklog/logs:/app/logs
    ports:
      - 1243:1243
    restart: unless-stopped
