version: "3"
services:

  watchtower:
    command:
      - --cleanup
      - --label-enable
    container_name: watchtower
    environment:
      - TZ=Europe/Brussels
    image: containrrr/watchtower:latest
    labels:
      com.centurylinklabs.watchtower: true
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# docker run --rm --pull=always --label com.centurylinklabs.watchtower.enable=true -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once --cleanup --label-enable

  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /volume1/docker/dashy/conf.yml:/app/public/conf.yml
    ports:
      - 4000:80
    # Set any environmental variables
    environment:
      - NODE_ENV=production
      - UID=1024
      - GID=101
      - TZ=Europe/Brussels
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=sdekunst.synology.me

      # Optional:
      - PASSWORD=$PASSWORD
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=10.10.10.10
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /volume1/docker/wgeasy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      com.centurylinklabs.watchtower.enable: true

  glances:
    image: 'nicolargo/glances:latest-full'
    container_name: glances
    restart: unless-stopped
    ports:
        - '61208-61209:61208-61209'
    environment:
        - GLANCES_OPT=-w
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock:ro'
    pid: host
    labels:
      com.centurylinklabs.watchtower.enable: true

  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: unless-stopped
    ports:
        - '19999:19999'
    volumes:
        - '/proc:/host/proc:ro'
        - '/sys:/host/sys:ro'
        - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
        - PGID=0
