version: "3"
services:

  archisteamfarm:
    image: justarchi/archisteamfarm:latest
    container_name: ASF
    environment:
      - TZ=Europe/Brussels
    volumes:
      - /volume1/docker/asf/config:/app/config
      - /volume1/docker/asf/logs:/app/logs
    ports:
      - 1242:1242
    restart: unless-stopped
  archisteamfarmsdklog:
    image: justarchi/archisteamfarm:latest
    environment:
      - TZ=Europe/Brussels
    container_name: ASFsdklog
    volumes:
      - /volume1/docker/archisteamfarmsdklog/Nlog.config:/app/NLog.config
      - /volume1/docker/archisteamfarmsdklog/config:/app/config
      - /volume1/docker/archisteamfarmsdklog/logs:/app/logs
    ports:
      - 1243:1243
    restart: unless-stopped

# NLog.config for SDK logging:configs:
# <?xml version="1.0" encoding="utf-8" ?>
# <nlog xmlns="https://nlog-project.org/schemas/NLog.xsd" xsi:schemaLocation="NLog NLog.xsd" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance">
#   <targets>
#     <target xsi:type="ColoredConsole" name="ColoredConsole" layout="${date:format=yyyy-MM-dd HH\:mm\:ss}|${processname}-${processid}|${level:uppercase=true}|${logger}|${message}${onexception:inner= ${exception:format=toString,Data}}" />
#     <target xsi:type="File" name="File" archiveFileName="${currentdir}/logs/log.{#}.txt" archiveNumbering="Rolling" archiveOldFileOnStartup="true" cleanupFileName="false" concurrentWrites="false" deleteOldFileOnStartup="true" fileName="${currentdir}/log.txt" layout="${date:format=yyyy-MM-dd HH\:mm\:ss}|${processname}-${processid}|${level:uppercase=true}|${logger}|${message}${onexception:inner= ${exception:format=toString,Data}}" maxArchiveFiles="10" />
#     <!-- Below becomes active when ASF's IPC interface is started -->
#     <target type="History" name="History" layout="${date:format=yyyy-MM-dd HH\:mm\:ss}|${processname}-${processid}|${level:uppercase=true}|${logger}|${message}${onexception:inner= ${exception:format=toString,Data}}" maxCount="20" />
#     <target xsi:type="File" name="ChatLogFile" fileName="${currentdir}/logs/${event-properties:item=ChatGroupID}-${event-properties:item=ChatID}${when:when='${event-properties:item=ChatGroupID}' == 0:inner=-${event-properties:item=SteamID}}.txt" layout="${date:format=yyyy-MM-dd HH\:mm\:ss} ${when:when='${event-properties:item=Echo}' == true:inner=SDK---&gt;:else=${event-properties:item=SteamID}&lt;------} ${event-properties:item=Message}&#xA;" enableFileDelete="false"/>
#   </targets>
#   <rules>
#     <logger name="*" minlevel="Debug" writeTo="ColoredConsole" />
#     <logger name="*" minlevel="Debug" writeTo="File" />
#     <!-- Below becomes active when ASF's IPC interface is started -->
#     <logger name="*" minlevel="Debug" writeTo="History" />
#     <logger name="SDK" level="Trace" writeTo="ChatLogFile" />
#   </rules>
# </nlog>