version: "3"
services:

  watchtower:
    command:
      - --cleanup
      - --label-enable
    container_name: watchtower
    environment:
      - TZ=Europe/Brussels
    image: containrrr/watchtower:latest
    labels:
      com.centurylinklabs.watchtower: true
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# docker run --rm --pull=always --label com.centurylinklabs.watchtower.enable=true -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once --cleanup --label-enable