version: "3"
services:

  archisteamfarm:
    image: justarchi/archisteamfarm:latest
    container_name: ASF
    volumes:
      - /volume1/docker/asf/config/Nlog.config:/app/NLog.config
      - /volume1/docker/asf/config:/app/config
      - /volume1/docker/asf/log:/app/log
    ports:
      - 1242:1242
    restart: unless-stopped
  archisteamfarmsdklog:
    image: justarchi/archisteamfarm:latest
    container_name: ASFsdklog
    volumes:
      - /volume1/docker/archisteamfarmsdklog/config/Nlog.config:/app/NLog.config
      - /volume1/docker/archisteamfarmsdklog/config:/app/config
      - /volume1/docker/archisteamfarmsdklog/log:/app/log
    ports:
      - 1243:1243
    restart: unless-stopped
