version: "3"
services:

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - TZ=Europe/Brussels
      - PGID=101
      - PUID=1024
    labels:
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - /volume1/docker/bazarr/config:/config
      - /volume1/Anime:/volume1/Anime
      - /volume1/Movies:/volume1/Movies
      - /volume1/Series:/volume1/Series
    ports:
      - 6767:6767
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - TZ=Europe/Brussels
      - PGID=101
      - PUID=1024
    labels:
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - /volume1/docker/jackett/config:/config
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1024
      - PGID=101
      - TZ=Europe/Brussels
    labels:
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - /volume1/Downloads:/volume1/Downloads
      - /volume1/Movies:/volume1/Movies
      - /volume1/docker/radarr/config:/config
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=Europe/Brussels
      - PGID=101
      - PUID=1024
    labels:
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/Series:/volume1/Series
      - /volume1/Anime:/volume1/Anime
      - /volume1/Downloads:/volume1/Downloads
    ports:
      - 8989:8989
    restart: unless-stopped
